name = "gravity-maze-backend"
main = "worker.js"
compatibility_date = "2025-01-01"

[[durable_objects.bindings]]
name = "REG"
class_name = "Registry"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Registry"]
