plugins {
    id 'com.android.application'
}

android {
    namespace 'com.gravitymaze.game'
    compileSdk 35

    defaultConfig {
        applicationId "com.gravitymaze.game"
        minSdk 21
        targetSdk 35
        versionCode 1
        versionName "1.0.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

dependencies {
    implementation 'com.google.androidbrowserhelper:androidbrowserhelper:2.5.0'
}
